apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
  labels:
    app: my-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-webapp
  template:
    metadata:
      labels:
        app: my-webapp
    spec:
      containers:
      - name: app-container
        image: asia-east1-docker.pkg.dev/molten-snowfall-401102/my-repository/python-app:1.1
        ports:
        - containerPort: 8000