apiVersion: v1
kind: Service
metadata:
    name: my-service
    labels:
      app: my-webapp
    annotations:
        cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: my-webapp
  ports:
    - port: 8000
      targetPort: 8000
